In [1]:
#Numpy - base for major data science libraries like pandas.

#Numpy is a multi-dimensional array library..one can store 1d,2d,3d,4d..arrays data.

#Lists are slow..meanwhile numpy is fast..because numpy uses FIXED TYpe ....numpy uses less bytes of memory..while lists  allocate memory for size , reference count
#...object type and object value of each number , there by allocating more memory than. umpy , hences slow

#one more reason numpy is faster is becaus when we iterate through each item in numy , we dont have to type check like in lists, if the item is a number of string or etc etc

#numpy uses continues memory unlike lists where data is scattered around

#as computers use SIMD ( single instruction multiple data ) it can perform operatio/computations quicker is data is in together in sseries rather than scattered in lists

#numpy has effective cache utilization

#Numpy can do same tasts as Lists like insertion , deletion , appending , concatination....but also lots and lots of tasks more

# applications of numpy..!1) Mathematics ( matlab replacement ) , 2) plotting ( Matlab ) , 3) Backend (pandas, connect4, digital photagraphy)

#machine learning applications 





# Basics

In [2]:
import numpy as np

In [3]:
#how to initialise an array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[9.0,8.0,7.0,5.6],[6.0,3.0,4.5,9.4]])
b

array([[9. , 8. , 7. , 5.6],
       [6. , 3. , 4.5, 9.4]])

In [5]:
#number of dimensions
a.ndim

1

In [6]:
b.ndim

2

In [7]:
#get shape
a.shape

(3,)

In [8]:
b.shape

(2, 4)

In [9]:
#get typr
a.dtype

dtype('int64')

In [10]:
b.dtype

dtype('float64')

In [11]:
#size
a.size

3

In [12]:
b.size

8

In [13]:
#itemsize
a.itemsize

8

In [14]:
#total size
#number of bytes = seze * itemsize
a.nbytes
b.nbytes

64

# Accessing/Changing specific elements , rows , columns, etc

In [15]:
a = np.array([[1,2,3,4,5,6,7,8,9],[2,4,3,7,8,3,5,4,5]])
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [2, 4, 3, 7, 8, 3, 5, 4, 5]])

In [16]:
#get a specific element [r,c]
a[1,2]
a[1,2]




3

In [17]:
#get a specific row
a[0,1:9:2]

array([2, 4, 6, 8])

In [18]:
#get a specific column
a[:,2]

array([3, 3])

In [19]:
a[0,1:9:2]

array([2, 4, 6, 8])

In [20]:
a[1:3:2,0]

array([2])

In [21]:
#replacing an array

a[1,5]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  3,  7,  8, 20,  5,  4,  5]])

In [22]:
a[:,2]=20
a

array([[ 1,  2, 20,  4,  5,  6,  7,  8,  9],
       [ 2,  4, 20,  7,  8, 20,  5,  4,  5]])

In [23]:
a[2:2,2:2]=20
a

array([[ 1,  2, 20,  4,  5,  6,  7,  8,  9],
       [ 2,  4, 20,  7,  8, 20,  5,  4,  5]])

In [24]:
a[0:,3:5]=30
a

array([[ 1,  2, 20, 30, 30,  6,  7,  8,  9],
       [ 2,  4, 20, 30, 30, 20,  5,  4,  5]])

In [25]:
#3d example

b = np.array([[[2,3,5,6],[4,3,5,6]],[[2,3,4,5],[1,3,2,4]]])
b

array([[[2, 3, 5, 6],
        [4, 3, 5, 6]],

       [[2, 3, 4, 5],
        [1, 3, 2, 4]]])

In [26]:
b.shape

(2, 2, 4)

In [27]:
#to get sepecific element ( dimenstion , row , column)
b[0,1,3]

6

In [28]:
b[:,1:2:2,:]

array([[[4, 3, 5, 6]],

       [[1, 3, 2, 4]]])

In [29]:
# to replace

b[:,1,:]=[9]
b

array([[[2, 3, 5, 6],
        [9, 9, 9, 9]],

       [[2, 3, 4, 5],
        [9, 9, 9, 9]]])

# initializing different types of arrays

In [30]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3,4,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [32]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [33]:
#random numbers

np.random.randint(6,size=(3,4))

array([[4, 2, 2, 5],
       [4, 4, 1, 0],
       [0, 0, 2, 1]])

In [34]:
#identity matrix

np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
#to repeat an array

arr=([[2,3],[4,5]])
arr

[[2, 3], [4, 5]]

In [36]:
repeat_array = np.repeat(arr,6,axis=1)
repeat_array

array([[2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5]])

In [37]:
# task to print  array([[1., 1., 1., 1., 1.],
#                       [1., 0., 0., 0., 1.],
#                       [1., 0., 9., 0., 1.],
#                       [1., 0., 0., 0., 1.],
#                       [1., 1., 1., 1., 1.]])

z=np.ones((5,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
z[1:4,1:4]=0
z


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
z[2,2]=9
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
#be carefull when copying arrays

r = np.array([1,2,3])
r

array([1, 2, 3])

In [41]:
h=r
h

array([1, 2, 3])

In [42]:
h[1]=5
h

array([1, 5, 3])

In [43]:
# when you change the duplicate array , the original array also chanages
r

array([1, 5, 3])

In [44]:
#hence use copy function
r = np.array([1,2,3,4,5])
h = r.copy()
h[3]=9
print(r)
print(h)


[1 2 3 4 5]
[1 2 3 9 5]


# MATHEMATICS

In [45]:
p = np.array([2,3,4,5,6])



In [46]:
#basic operations on arrays
print(p+2)
print(p-2)
print(p*2)
print(p/2)

[4 5 6 7 8]
[0 1 2 3 4]
[ 4  6  8 10 12]
[1.  1.5 2.  2.5 3. ]


In [47]:
g=np.array([2,4,6,3,4])
print(p+g)
print(p*g)
print(p-g)
print(p/g)

[ 4  7 10  8 10]
[ 4 12 24 15 24]
[ 0 -1 -2  2  2]
[1.         0.75       0.66666667 1.66666667 1.5       ]


### linear algebra 

In [57]:
a= np.ones((4,3))
print(a)

b= np.full((3,8),4)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4]]


In [58]:
# print(a*b)doesnt work because they are of different sizes
#hence use matrix multiplication

np.matmul(a,b)

array([[12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12.]])

In [68]:
#find the determinant

d = np.ones((5,5))
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
np.linalg.det(d)

0.0

In [71]:
d[1:4,1:4] = 6
d

array([[1., 1., 1., 1., 1.],
       [1., 6., 6., 6., 1.],
       [1., 6., 6., 6., 1.],
       [1., 6., 6., 6., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
np.linalg.det(d)


0.0

### statistics

In [74]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
np.min(stats)
np.max(stats)

6

In [77]:
np.sum((stats),axis=1)

array([ 6, 15])

# reorganizing arrays

In [81]:
prior=np.array([[[1,2,3,4],[5,4,3,6]],[[1,2,3,4],[2,5,4,6]]])
prior


array([[[1, 2, 3, 4],
        [5, 4, 3, 6]],

       [[1, 2, 3, 4],
        [2, 5, 4, 6]]])

In [82]:
prior.shape

(2, 2, 4)

In [85]:
later = prior.reshape((2,4,2))
later

array([[[1, 2],
        [3, 4],
        [5, 4],
        [3, 6]],

       [[1, 2],
        [3, 4],
        [2, 5],
        [4, 6]]])

In [88]:
#vertical staking vectors

array1 = np.array([1,2,3,4])
array2 = np.array([3,2,4,5])

vstack1 = np.vstack([array1,array2])
#vstack2 = np.add([array1,array2])
print(vstack1)
#print(vstack2)

[[1 2 3 4]
 [3 2 4 5]]


In [89]:
#horizontalstack

array1 = np.array([1,2,3,4])
array2 = np.array([3,2,4,5])

vstack1 = np.hstack([array1,array2])
print(vstack1)

[1 2 3 4 3 2 4 5]


# miscellaneous

In [96]:
#load data from file

data = np.genfromtxt('test.csv',delimiter = ',')
#data.astype('int32') to change data to required data type...int 32 in this case
data = data.astype('int32')
data

array([[-2147483648, -2147483648, -2147483648, -2147483648],
       [          1,           1, -2147483648, -2147483648],
       [          1,           1, -2147483648, -2147483648],
       ...,
       [         45,          98, -2147483648, -2147483648],
       [         45,          98, -2147483648, -2147483648],
       [         45,          98, -2147483648, -2147483648]], dtype=int32)

# boolean masking and advanced indexing

In [97]:
data > 30 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False]])

In [98]:
data[data>40]

array([41, 41, 41, ..., 98, 45, 98], dtype=int32)

In [100]:
np.any(data>70 , axis=0)

array([False,  True, False, False])

In [104]:
((data>30 )& (data<90))

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False]])